# Generated by Django 4.2.25 on 2025-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(db_index=True, default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="stripe_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment_status",
            field=models.CharField(db_index=True, default="inactive", max_length=20),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro")],
                db_index=True,
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_pa_user_id_3e0999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_a2ce56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["payment_status", "end_date"],
                name="payments_su_payment_24ac73_idx",
            ),
        ),
    ]
