# Generated by Django 4.2.25 on 2025-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymenttransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                db_index=True,
                default="stripe",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="paypal_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
