# Generated by Django 4.2.25 on 2025-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_disabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("basic", "Basic User"),
                    ("pro", "Pro User"),
                ],
                db_index=True,
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_verified"], name="accounts_us_email_0636d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="accounts_us_role_2b136f_idx"
            ),
        ),
    ]
